### ISSUE TITLE
Custom Fuzzer values not shrinking correctly

### ISSUE THREAD

**Issue by ckoster22** [elm-community/elm-test#105]
I'm experimenting with the `Fuzz` module and writing my own Fuzzer. In this example I use `andThen` a few times to generate 3 random Msgs. The three Msgs are `FetchNames`, `FetchNamesSucceed`, and `FetchNamesFail`

I wrote a test that says whenever the third Msg is `FetchNamesSucceed` then assert that a record's error field is `Nothing`. I deliberately put a bug in the supplied update function to cause the test to fail in some situations.

The test does fail but the shrunken output displayed is wrong.

```
↓ All tests
✗ Testing random 3 Msgs

Given (FetchNamesFail "There was an error",FetchNames,FetchNamesFail "There was an error")

    Just "There was an error"
    ╷
    │ Expect.equal
    ╵
    Nothing


Given (FetchNamesFail "There was an error",FetchNames,FetchNamesSucceed [])

    Just "There was an error"
    ╷
    │ Expect.equal
    ╵
    Nothing



TEST RUN FAILED

Duration: 27 ms
Passed:   0
Failed:   1
```

The first part says `Given (FetchNamesFail "There was an error",FetchNames,FetchNamesFail "There was an error")` which isn't sensible because the expectation only happens if the third msg in the tuple is `FetchNamesSucceed`. *This is the problem that I'm opening this issue for*

Apologies for the long example. This is as small as I can get it while still reproducing the incorrect output.

```
import Test exposing (..)
import Expect
import Fuzz exposing (Fuzzer, andThen)


advancedExample : Test
advancedExample =
    fuzz threeMsgFuzzer "Testing 3 random Msgs" <|
        \( firstMsg, secondMsg, thirdMsg ) ->
            let
                endState =
                    { error = Nothing }
                        |> updateState firstMsg
                        |> updateState secondMsg
                        |> updateState thirdMsg
            in
                case thirdMsg of
                    FetchNamesSucceed _ ->
                        let
                            expectation =
                                Expect.equal Nothing endState.error

                            _ =
                                if expectation /= Expect.pass then
                                    Debug.log "msgs" ( firstMsg, secondMsg, thirdMsg )
                                else
                                    ( firstMsg, secondMsg, thirdMsg )
                        in
                            expectation

                    _ ->
                        Expect.pass


threeMsgFuzzer : Fuzzer ( Msg, Msg, Msg )
threeMsgFuzzer =
    firstMsgFuzzer
        |> andThen secondMsgFuzzer
        |> andThen thirdMsgFuzzer


firstMsgFuzzer : Fuzzer Msg
firstMsgFuzzer =
    Fuzz.map
        (\randInt ->
            if randInt == 1 then
                FetchNames
            else if randInt == 2 then
                FetchNamesSucceed []
            else
                FetchNamesFail "There was an error"
        )
        (Fuzz.intRange 1 3)


secondMsgFuzzer : Msg -> Fuzzer ( Msg, Msg )
secondMsgFuzzer msg =
    case msg of
        FetchNames ->
            Fuzz.map
                (\randBool ->
                    if randBool then
                        ( msg, FetchNamesSucceed [] )
                    else
                        ( msg, FetchNamesFail "There was an error" )
                )
                Fuzz.bool

        _ ->
            Fuzz.constant ( msg, FetchNames )


thirdMsgFuzzer : ( Msg, Msg ) -> Fuzzer ( Msg, Msg, Msg )
thirdMsgFuzzer ( firstMsg, secondMsg ) =
    case secondMsg of
        FetchNames ->
            Fuzz.map
                (\randBool ->
                    if randBool then
                        ( firstMsg, secondMsg, FetchNamesSucceed [] )
                    else
                        ( firstMsg, secondMsg, FetchNamesFail "There was an error" )
                )
                Fuzz.bool

        _ ->
            Fuzz.constant ( firstMsg, secondMsg, FetchNames )


type Msg
    = FetchNames
    | FetchNamesSucceed (List String)
    | FetchNamesFail String


type alias State =
    { error : Maybe String }


updateState : Msg -> State -> State
updateState msg state =
    case msg of
        FetchNames ->
            state

        FetchNamesSucceed names ->
            state
            -- Uncomment this line to make the test pass
            --{ state | error = Nothing }

        FetchNamesFail error ->
            { state | error = Just error }
```

You'll notice I'm also using `Debug.log` to output the tuple when the test doesn't pass and that output correctly shows that the test fails when the first Msg is `FetchNamesFail` and the third Msg is `FetchNamesSucceed`, but the elm-test output says differently.

**Comment by rtfeldman** [comment]
So to summarize: the `Given` output is inaccurate.

It's claiming that a different value was used to obtain this failure than the value that was actually used. We know this because:

1. The value it claimed it to have failed on cannot possibly lead to a failure.
2. `Debug.log` confirms that a different value than the stated one led to the failure.

Shrinking is a reasonable place to look, since in the absence of shrinking, `Given` is a trivial passthrough.

Does that seem plausible @mgold?

**Comment by ckoster22** [comment]
That is an accurate summary, thanks.

**Comment by mgold** [comment]
`Fuzz.andThen` is a "here be dragons" piece of code, and it's entirely possible the `given` is being written incorrectly somewhere.

But as a workaround, instead of chaining `andThen`, can you generate some int or union type that corresponds to all possible triples of tags that you want to allow, and then `map` over it to get that triple? Or even `Fuzz.frequency` would allow you to weight the different triples as you please.

**Comment by ckoster22** [comment]
There's a specific reason that I'm using `andThen`.

I'm mimicking a situation where only a specific order of Msgs are valid. `threeMsgFuzzer` is using the following strategy:

* `FetchNames` always precedes `FetchNamesSucceed` or `FetchNamesFail`. In other words, you'll never have `FetchNamesSucceed` directly followed by `FetchNamesFail`, or vice versa.
* Two consecutive Msgs will never be the same. (You can't have a `FetchNames` followed by `FetchNames`)
* Pick a random first msg and randomly generate the second and third msg using the above rules as a constraint.

`Fuzz.frequency` would not achieve this constrained behavior as far as I can tell which is why I use `Fuzz.andThen`.

Taking a step back and talking about this more generally, is this an issue when using `Fuzz.andThen` with Union Types? Or is `Fuzz.andThen` generally not recommended for use?

**Comment by rtfeldman** [comment]
> Taking a step back and talking about this more generally, is this an issue when using `Fuzz.andThen` with Union Types?

Nah, it works the same way for whatever you give it.

> Or is `Fuzz.andThen` generally not recommended for use?

Not except in the sense that it seems like it may currently have a bug. 😉 

I read @mgold's "Here there be dragons" as a comment on how tricky `Fuzz.andThen`'s implementation is, and how likely there is to be a bug somewhere in it/how hard it'll be to fix. 😄

**Comment by mgold** [comment]
>> Or is `Fuzz.andThen` generally not recommended for use?

>Not except in the sense that it seems like it may currently have a bug. 

Well there is #62 as a case of it doing something "wrong" that isn't worth debugging. It's a very challenging implementation, with shrinking only so effective (as is in evidence!), so taking alternate approaches is sometimes fruitful.

You can use `Fuzz.frequency` to select one of the possible triples that satisfy your constraints. For starters, your implementation does not follow those constraints: `firstMsgFuzzer` may generate one of any of the message types, but `FetchNames` must always come first. So the first thing we need to pick is whether the second element is `FetchNamesSucceed` or `FetchNamesFail` (since it cannot be `FetchNames` by your second bullet point). As for the third element, it could be `FetchNames` again, or it could be the other of success or failure. Assuming another constraint that a single fetch cannot cause both a success and a failure, the only legal triples are `(FetchNames, FetchNamesSucceed [], FetchNames)` and `(FetchNames, FetchNamesFail "An error occurred", FetchNames)`, which you can get by mapping over a boolean.

I'm guessing that once you more precisely and correctly define your constraints, you will be able to write out all legal triples by hand and use `Fuzz.frequency` to pick among them.

**Comment by ckoster22** [comment]
I appreciate the advice on finding a suitable workaround. However, I very likely won't be the only person who comes across this bug.

If the resolution really is to take an alternate approach than using `Fuzz.andThen` can I suggest updating the `Fuzz.andThen` docs to reflect that advice for devs in the future who would try to do something similar?

I hope that's not the resolution and the root cause is fixed instead but that's obviously up to you guys.

**Comment by mgold** [comment]
I can update the docs and try to come up with a more minimal example.

**Comment by mgold** [comment]
Well, only a year and a half late, but this no longer reproduces.

```
↓ Issue105
✗ Testing 3 random Msgs

Given (FetchNamesFail "There was an error",FetchNames,FetchNamesSucceed [])

    Just "There was an error"
    ╷
    │ Expect.equal
    ╵
    Nothing
```
