### ISSUE TITLE
Expect.all / Expect.multiple / Expect.many

### ISSUE THREAD

**Issue by drathier** [elm-community/elm-test#137]
I've been missing a way to assert multiple things in the same test. There's `Expect.all` which allows checking a single set of inputs against multiple functions, but I would like to check multiple things with multiple inputs. This is mostly useful for sanity checking and validating data half-way through a longer test, which makes debugging easier.

My current implementation:

```
many : List Expect.Expectation -> Expect.Expectation
many expectations =
  case expectations of
    [] ->
      Expect.pass

    expectation :: expectations ->
      case Expect.getFailure expectation of
        Nothing ->
          many expectations

        Just _ ->
          expectation
```

Since nobody's pointed this out, I'm assuming you haven't encountered this yourselves. Is this because you're writing multiple tests to test these different things? Is it because you simply couldn't add more expectations in the same test? Or do you already have something like this?

Would you add more expectations if it was a possibility? What's the risk that people start writing huge tests because of this? Would that be a bad thing?

**Comment by rtfeldman** [comment]
This occurred to me awhile back. My conclusion is that doing sanity checks as separate tests take slightly more time to write, but they result in clearer failure messages—and that's the right thing to prioritize.

The alternative is that a sanity check fails and the message has nothing to do with what the test says it's doing - e.g. `test "it returns 42" failed because "halibut" was not equal to "salmon"`

**Comment by mgold** [comment]
I'm generally on-board with Richard that tests should be small and independent. A test like this will mask all but the first failure and it's hard to see the extent of the problem.

`Expect.all` is best used when one **semantic quality** requires multiple **independent, specific expectations**. The canonical example is a number is within a range. Another possibility is some complex set of expectations on a record (e.g. x and y velocity should both be zero).

If you want sanity checking midway through a test, you might be able to pull those things out into their own test, if they make sense on their own. Otherwise, maybe your test is too complicated, perhaps indicating a poorly designed API?

**Comment by drathier** [comment]
Turns out I've written this exact function as `expectAll` in another project before. In that project I tested that the merge function of a CRDT was associative, commutative and idempotent for all inputs. The setup code is quite large, but sure, that could've been 3 tests. The other test that used `expectAll` checked a 3-way symetric relation, along the lines of `(a+b)-a=b` and `(a+b)-b=a`. Without `expectAll` I probably would've only checked one of those relations, and hoped for the fuzzer to find the errors anyway.

In the current project, I'm implementing a data structure. The test for the remove function was failing, so being able to sanity check the input helped me zero in on the error. I checked that the data structure wasn't empty after my inserts had run, and that the remove function actually modified the data structure. Then I checked it using the actual api, which would be the only expectation if I didn't use `many`. 

The sanity checks help find typos or mistakes in the test itself. For example, removing a key that doesn't exist is a no-op, so passing the wrong key to `remove` silently fails, and then asking for that same key doesn't yield a result, just as expected, but for the wrong reason.

**Comment by mgold** [comment]
> The setup code is quite large, but sure, that could've been 3 tests.

Especially if you extract a function or a fuzzer!

> checked a 3-way symetric relation

You can do this as multiple tests nested under a single `describe` to capture how it's a single relationship. In fact this will show you if one equality is failing or if all of them are -- although separate tests will have separate inputs -- but the more precise reporting makes individual tests must better than ` foo == bar && bar == qux && foo == qux |> Expect.true "something failed but I don't know which one"`.

> I checked that the data structure wasn't empty after my inserts had run

This can be a separate test. If you're worried about copying code, extract a function that inserts into the data structure. Call that function in a test to assert the data structure is nonempty. Then call the function again in your remove test. Or do the same thing with a `nonemptyStructure` fuzzer.

Tests should focus on calling the code under test and setting an expectation. Setup code should be moved out.

**Comment by drathier** [comment]
I'll close this and see how I can change the way I write tests. I haven't really had this problem after following your advice @mgold, but I have also worked on things that are simpler to test.
