### ISSUE TITLE
Replace Test.filter with skip & only, auto-fail if used

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/elm-test#142]
The idea of `Test.only` and `Test.skip` has been discussed before:

* https://github.com/elm-community/elm-test/issues/88
* https://github.com/elm-community/elm-test/issues/44
* https://www.reddit.com/r/elm/comments/5w4x0g/elmtest_how_to_run_only_one_test/de7p7lh

That last link posed an interesting twist:

*What if we had `Test.only` and `Test.skip`, but using either of them auto-failed your test run?*

This way their use would be clear: they isolate which tests you want to focus on right now. You'd never commit them to your code base, because doing so would immediately fail your entire test run.

This would address the concern that @mgold [mentioned](https://github.com/elm-community/elm-test/issues/44#issuecomment-242940571):

> skipping and isolating tests makes for a more brittle test suite. It's too easy to commit a test suite with only one test actually running, or to leave dead code in a permanent skip state.

## What these would do

```elm
Test.skip : Test -> Test
```
This is a quick way to say "quit yelling at me, failing test, I'm working on other failures right now."

The wrapped test will not get run, but your whole test run will fail even if everything else passes. This way if you accidentally commit the `skip` instead of taking it back out again when you're done, you'll find out because your build will break.

```elm
Test.only : Test -> Test
```
This is a quick way to say "I only want to run this test right now."

Only the wrapped test (and other tests wrapped with `Test.only`) will get run and all others will get skipped. Once again, your whole test run will fail even if everything else passes, to guard against accidentally committing a `Test.only`.

## What these wouldn't do

Because of the auto-failure, [this use case](https://github.com/elm-community/elm-test/issues/44#issuecomment-242958580) would not be addressed:

> I have often been in the situation where a test needs to be disabled for a few weeks / months while an external issue is resolved. [...] I also agree that an easy way to ignore tests can make the whole suite brittle through an accidental checkin and I have previously had to setup CI tasks to spot such issues

I think these are mutually exclusive: either these have the anti-checkin guards or they don't.

To summarize my position on this: my experience is that if you have a "pending" set of tests that don't fail the build, the team soon becomes desensitized to seeing those messages in test output, making the "pending" feature no more effective than a `-- TODO FIXME` comment (and arguably less effective). I'm not sure how CI could change this, but maybe I'm missing something.

I still don't see a more effective way to check in temporarily disabled tests than to comment them out (signaling *"Here there be technical debt!"* in a way everyone viscerally understands) or to remove the busted tests outright—and in either case to file an issue for re-enabling the tests once whatever blocking condition has been resolved.

## Should `Test.filter` still exist if these do?

If it does, it should clearly auto-fail the test run as well - as @benansell [noted](https://github.com/elm-community/elm-test/issues/44#issuecomment-242958580).

However, my default assumption is that it would be a worse way to do the same thing. The only way I've ever used features like `Test.filter` (or `--grep` in Mocha) was to isolate tests, and I can't think of a situation where I'd want to use it instead of `Test.only` or `Test.skip`.

If we're adding 2 functions to the API, I'd like to simultaneously remove the one that seems like a worse version of the newcomers. We can always add it back as a minor version bump if there's demand in a post-`only` world.

**Comment by drathier** [comment]
This works at the `describe` level as well, right?

**Comment by rtfeldman** [comment]
Yep! Each would be `Test -> Test` functions, so you could wrap whatever you like - including a `describe`.

**Comment by mgold** [comment]
Richard and I discussed this in person and putting `only` on a describe will include everything under it. Nested `only`s have no effect.

We also discussed a "stop after first failure" and "rerun only what failed last time" command-line options (the rerun will need stored state across test runs) and concluded they were compatible with each other and `only`. These options will not land immediately, and will give us insight into building towards a "watch mode", where the test runner stays running between tests and watches file changes.

I like `skip` in principle, since it is the dual of `only`. Think mute and solo from audio, or isolation and masking in the [Prim 9](http://stat-graphics.org/movies/prim9.html).

That said, we haven't had the conversation to make sure that adding `skip` doesn't cause any weird semantic clashes with `only` and the two future options.

+1 for removing filter.

**Comment by drathier** [comment]
"Nested `onlys` have no effect."; so the outermost one(s) have priority over any `only` and `skip` it covers?

**Comment by mgold** [comment]
An `only` within an `only` and a `skip` within a `skip` should have no effect. But it's less clear what happens here:

```elm
only <| describe "skip within only"
  [ skip <| aTest
  , anotherTest
  ]
```

and here:

```elm
skip <| describe "only within skip"
  [ only <| aTest
  , anotherTest
  ]
```

In the first example, I think the `skip` should be meaningful and `aTest` will not be run. In the second, I think the `only` should be ignored and neither `aTest` nor `anotherTest` should run. In other words, `skip` takes priority.

But I'm open to different opinions.

**Comment by rtfeldman** [comment]
I agree on both counts! ☝️

**Comment by drathier** [comment]
I also agree. That should also skip both `only <| skip` or `skip <| only` for us. I wouldn't be surprised to see those combinations being used; this is highly temporary code after all.

**Comment by mgold** [comment]
Should `only <| skip` cause no tests to be run, if there are no other `only`-s in the program?

**Comment by drathier** [comment]
Can we allow multiple `only`, to run a set of relevant tests?

I think I'd mean for those combinations to both mean "skip this test, I want to run other tests now", or for `only <| skip` to be invalid. Being able to disable all tests by putting that combination anywhere in the test suite seems kinda useless; if you really want to skip all tests you'd `skip` the outermost `describe` in `all` (but when would you ever want to do that?). 

I can see myself doing something like this, on this test tree:

tests:
- describe a
  - test a1
  - test a2
- describe b
  - test b1

1. change something
2. fail a ton of tests because of that change
3. recursively search for the root cause: `only` run `describe a` to see if test suite still fails; it does
4. since it failed, add `only` to `test a1`, see if suite still fails; it does
5. since `a1` is a complicated test, like `fuzz acyclicGraphFuzzer "isAcyclic returns True for all directed acyclic graphs"`, we want to figure out what caused it. Maybe something in `b` is the cause?
6. add `skip` to `describe a`, making it `skip <| only`. Then add `only` to `b`. 
7. see if `describe b` fails; it does
8. add `only` to `b1`, ...
9. current state of the test suite now looks like this:

tests:
- skip <| only <| describe a
  - only <| test a1
  - test a2
- only <| describe b
  - only <| test b1

where `describe c`, `describe d` etc. don't have any `skip` or `only` modifiers. In the current state, only `b1` would run. 

10. if `b1` is also too complicated, we might go onto `describe c` and continue recursively from step 3. Otherwise, we fix the test and start unwinding the stack the same way we got here, making sure tests pass along the way. 

I know I could remove those `only`s rather than skipping them, but when I'm bug hunting I'm really not inte mood to clean up after myself as I go. Finding that bug is the top priority. When I've fixed it I'll go back and remove the modifiers. Also, the trail of `only`s help me find out what tests I've looked at before, which means I can go back to something I have somewhat fresh in memory when finding any other bugs.

**Comment by rtfeldman** [comment]
@drathier This motivation makes sense to me.

So basically "An `only` has no effect if it wraps one or more `only` tests," yeah?

**Comment by mgold** [comment]
Wait, so we use the **innermost** only?

```elm
describe "a test suite"
  [ only <| describe "a subsuite"
    [ only <| testA
    , testB
    ]
  , testC
  ]
```
Obviously `testA` gets run and `testC` does not. What about `testB`? I'm not sure what makes more sense.

**Comment by drathier** [comment]
Yeah, I'd say the innermost `only`(s) makes more sense, so `testB` should not run in your case. I'd also expect `testD` to not run in the below example, since `describe "a subsuite"` has an `only` modifier:

```
describe "a test suite"
  [ only <| describe "a subsuite"
    [ only <| testA
    , testB
    ]
  , describe "another subsuite" 
    [ only <| testD
    ]
  ]
```

but I'm not quite sure how to formalize this rule. Maybe something like this?

* if any thing in describe has a `skip` modifier, ignore them
* if any non-ignored thing in describe has `only` modifier, ignore those that don't
* recurse down all non-ignored things

**Comment by mgold** [comment]
What about:
* Each subtree has a priority label that defaults to zero
* `skip` applies a large negative priority
* `only` increments the priority compared to the parent
* Figure out what the highest priority is in the whole tree
* Run only subtrees that have that priority.

The "`only`-ies don't nest" algorithm is a little simpler:
* Ignore anything under a `skip`, even if it's under an `only` higher up
* Keep a list of what's been `only`-ed and not `skip`ped
* Run everything in that list, or if it's empty, everything not `skip`ped

**Comment by rtfeldman** [comment]
I'm starting to think "easy to explain what it does" might outweigh "minimizes amount of editing you need to do when narrowing things down." 🤔 

Especially considering long-term there will probably be CLI flags and/or editor integrations that people would use instead of calling `only` or `skip` directly...

**Comment by mgold** [comment]
Yup, I agree with that. I think it's fairly intuitive and explainable that:

* Anything under a `skip` never gets run, ever.
* Anything under a `only` will get run, unless it's also under a `skip` (which could be higher or lower than the `only`)
* Anything under neither a `skip` nor an `only` will get run if `only` is not used
* Using `skip` or `only` anywhere will cause a "yellow" test run if no tests fail

**Comment by drathier** [comment]
I don't find the recursive explanation that much harder, especially with an example or trying it out yourself.

* Any path under a `skip` never gets walked down, ever.
* If a `describe` has an `only` directly beneath it, only walk down paths marked as `only`.
* Otherwise, walk down all paths
* If you reach a test, run it
* Using `skip` or `only` anywhere will cause a "yellow" test run (if no tests fail)

(maybe with the addition that `only <| skip` and `skip <| only` don't count towards the "If a `describe` has an `only` directly beneath it")

* Both versions make it hard to answer "why did/didn't this test run?", so maybe we should output the list of `only` and `skip` in the test suite when we get a "yellow" test run?
* If we're talking future IDE support: many unit test IDE integrations make failing tests clickable links to the source of that test. If you get a failing test, you could click on the `describe` chain on that failing test to get to the `describe`/`test` you want, add an `only`/`skip` and immediately run again. If you require the developer to search their way up the tree to remove any `only`s, that's going to slow down the search a lot.

Say, I want to focus down on `insertEdge` for this failing test case:
```
> Graph tests
> insertEdge
> Insert an edge with non-existant target node
```
I'd click `insertEdge`, the cursor moves to the start of that `describe`, I literally just type `only <|` and hit `ctrl+r` to rerun only those tests. Maybe it's a good idea to mark those rows with `only` in the output for the `describe´s that have the `only` modifier?
```
> Graph tests
> insertEdge (only)
> Insert an edge with non-existant target node
```
*  For the case of CLI tools integration or using the IDE UI to run a specific test, it shouldn't be much harder to implement with a recursive implementation.

**Comment by rtfeldman** [comment]
Closed via https://github.com/elm-community/elm-test/pull/144
