### ISSUE TITLE
Style question: `\_ ->` over `\() ->`?

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/elm-test#156]
**Note:** This is only a question about what style the examples, documentation, and suggested best practice for `elm-test` should follow. It wouldn't be a code change to the library itself.

Some time ago someone pointed out to me that you could do `\() ->` to "pattern match on `()`" instead of using `\_ ->` to indicate that you didn't care what the argument was, and wouldn't be using it. I liked that `\() ->` said more than `\_ ->` did, not just "we don't happen to care what this argument is," but rather "we *can't* care what this argument is, because it's always `()`."

Some time later @evancz commented (paraphrasing) that this seemed unnecessarily fancy. I've never thought much of the choice as a user, but as a teacher I've come around to that point of view. It seems that `elm-test` is the only common place where this syntax is used, which means it's de facto part of the learning curve of using `elm-test`.

It's not much learning if you're already familiar with the rest of Elm, but it is One More Thing to detour into explaining to beginners...and I'd definitely like beginners to use `elm-test` too.

Obviously anyone is free to continue using the `\() ->` style, but I now think `\_ ->` is the better choice to recommend in our documentation, examples, in `elm-test init`, etc.

Thoughts?

**Comment by drathier** [comment]
Sounds good to me. It's a bit easier to explain a wildcard pattern match than a unit type (empty tuple), and if elm-test is the only reason `\()` is used over `\_`, then we should change the docs.

**Comment by rluiten** [comment]
Id have to say the that the `\_` looks less busy so its a preference for that reason and only that reason.

**Comment by yormi** [comment]
I don't think it's a big deal to learn about the `\()` but since it's not necessary... KISS !? As you guys said, the least you have to worry about unecessary details, the best !

**Comment by knewter** [comment]
I prefer `\()` because if it's me and I see `\_` I am **immediately** sidetracked into trying to figure out what that argument is and if it can be useful to me. So for me, beginner or not, I was going to spend some time figuring out that function, and with `\()` it's more clear and faster for me to figure it out...I think.

**Comment by drathier** [comment]
@knewter I agree with everything you say. There's a big difference between `_`, which signals that I as a user do not care about this variable, and `()` which is a unit type, and thus signals that no information is sent. Thank you for changing my mind!

Thus, we have a good reason to choose `\()` over `\_`, so which one do we use?

**Comment by mgold** [comment]
Sure, but once you know that all unit tests take `()` and it's just a convention for laziness (... to enable parallelism), it shouldn't be too distracting. The whole point is that `()` is meaningless and not something you care about, so why draw attention to it?

**Comment by drathier** [comment]
I'm 100% sure I would've looked into what the ignored argument in my copy/pasted unit tests (the ones you get from `elm-test init` was when I first started using `elm-test`. I do that whenever I see an ignored or unused variable. 

I thought for a long time that `\()` was a lambda that took 0 arguments, and that the empty parentheses was just a syntax quirk of elm (since `\ -> 2` is a syntax error and looks a bit weird, but adding the parentheses fixes it), rather than a function that takes a single argument, an empty tuple, i.e. the built-in unit type.

**Comment by rtfeldman** [comment]
@drathier putting those two together, it sounds like `\_ ->` would have actually been clearer for you - you would have known it took 1 argument, looked up what it was, and saw that it was `()`, rather than thinking it was special syntax for an 0-arg function.

That (among the other factors here) makes me think `\_ ->` is the better choice for official documentation, although of course @knewter and others can continue using `\() ->` in your own tests!
