### ISSUE TITLE
Proposal: Fuzz.oneOf

### ISSUE THREAD

**Issue by Janiczek** [elm-community/elm-test#158]
Would this be worthwhile to have in `elm-test`?

```elm
{-| Fuzzer that chooses a value from a collection of values.
-}
oneOf : List a -> Fuzzer a
oneOf list =
    list
        |> List.map (\x -> ( 1, Fuzz.constant x ))
        |> Fuzz.frequency
```

Or a more general version that works on fuzzers instead of values:

```elm
{-| Fuzzer that chooses a fuzzer from a collection of fuzzers.
-}
oneOf : List (Fuzzer a) -> Fuzzer a
oneOf list =
    list
        |> List.map (\x -> ( 1, x ))
        |> Fuzz.frequency
```

(Version of this for old `frequency` can be found in [elm-test-extra](http://package.elm-lang.org/packages/ktonon/elm-test-extra/1.5.0/Fuzz-Extra#uniformOrCrash))

**Comment by mgold** [comment]
I'm mildly opposed since it's just a less powerful version of a function already provided, and can trivially be implemented by either the test author or the -extra library.

It also makes it harder to switch to a non-uniform frequency later on, which may prevent people from getting balances more appropriate for their test case. (Although, one could endlessly fiddle with the weights for a Msg fuzzer, and this would discourage that.)

**Comment by rtfeldman** [comment]
Having tried this, it's pretty great for `Msg` fuzzers, and at least so far, I don't think messing with the weights of `Msg` fuzzers is worthwhile.

> one could endlessly fiddle with the weights for a Msg fuzzer, and this would discourage that.

Yeah, my thought is that fiddling with them is the wrong default choice.

**Comment by Janiczek** [comment]
I think that for some tests non-uniform Msg weights are actually a good thing.

I understand the 'better to have that in -extra' argument :+1: and 'uniform' would probably be a better name to communicate the equal weights.
