### ISSUE TITLE
Feature request - Expose details of skipped tests in Test.Runner

### ISSUE THREAD

**Issue by stephenhand** [elm-community/elm-test#194]
I'm working on a karma plugin to run elm-test tests (https://github.com/stephenhand/karma-elm-test) and would ideally like to make the details of which tests were skipped during a test run available to reporters. As far as I can tell, it isn't possible to discern exactly what was skipped in a run using the current run (although I'm still upskilling in elm so could be mistaken)

Would it be possible for the runner to expose which tests in the test run were skipped somehow? Either a separate function that just retrieves what is skipped or a way of specifying for them to be included in the fromTest output as stubs?

**Comment by mgold** [comment]
Related to #179

**Comment by rtfeldman** [comment]
@stephenhand Can you tell me more about what the info would allow? What's the intended design from the end user's perspective?

**Comment by stephenhand** [comment]
@rtfeldman The specific use case I have in mind is, when providing the Karma runner with the result of an individual test you can set a 'skipped' flag in the data you provide, then reporter plugins can include details of which tests were explicitly skipped in their output. 

I've found it a useful feature in the past, for those times when developers working on a feature need to temporarily disable some tests whilst something is a work in progress but intend to reenable them (or at least reimplement tests covering the same functionality). It gives people looking at the test output of the CI system a better idea of what's happening than just an unexplained drop in the number of tests / coverage would do (and helps ensure devs remember to reenable or remove the tests in question later).  So I thought it might be useful information to make available for any runner implementation.

**Comment by rtfeldman** [comment]
> helps ensure devs remember to reenable or remove the tests in question later

Ah, so in `elm-test`, using `skip` fails the build automatically. It's designed to be used only during local testing sessions, and never checked in. Same with `only` and `todo`.

The reason is that, in my experience with testing systems that do not fail the build when these things are used, they end up getting checked in and left ignored for months or even years.

This policy acts as a forcing function: if you really want to disable some tests as a short-term hack to get the suite passing, it should *feel* like a short-term hack. Commenting tests out makes it obvious to anyone coming across the code later that a short-term hack has taken place (which it has), and when people see code that's been lying around commented-out for a long time, they feel the urge to either delete it or fix it (which is a good urge in this case).

**Comment by stephenhand** [comment]
I know elm-test reports 'failed' on a skip (which I think is a good idea) but a couple of points:
1. Even if skipped tests fail a test run, it must be better to report exactly which skipped tests failed the build to the user rather than making them go looking (given that it might be a different user trying to fix the build than the one who broke it, or indeed the same, albeit forgetful user...) ?
2. Alternative test runners needn't abide by the elm-test decision on whether a run has passed or failed, they have been provided with enough data to make their own decision, so not exposing the details of the skipped tests doesn't prevent alternative runners passing runs with skipped tests, it just means they can provide less information.

**Comment by rtfeldman** [comment]
> Even if skipped tests fail a test run, it must be better to report exactly which skipped tests failed the build to the user rather than making them go looking (given that it might be a different user trying to fix the build than the one who broke it, or indeed the same, albeit forgetful user...) ?

I totally appreciate this concern, but `skip` and `only` have been out for awhile now, and so far we aren't hearing reports that this is a problem in practice.

Exposing this API would impose future design constraints on us, and I don't think that cost is worth paying until we've gotten enough reports to (1) confirm the problem is happening in a significant number of cases, and (2) have enough data points to understand what it looks like when it happens.

> Alternative test runners needn't abide by the elm-test decision on whether a run has passed or failed, they have been provided with enough data to make their own decision, so not exposing the details of the skipped tests doesn't prevent alternative runners passing runs with skipped tests, it just means they can provide less information.

If others disagree with our design decisions, I think it makes more sense for them to build their own API than for us to try to accommodate both ours and theirs! 😉

**Comment by stephenhand** [comment]
Ok, that's cool, I know it's not a big thing so if it doesn't fit on your roadmap and there hasn't been demand for it, it wouldn't make sense for you to do it.

Thanks for the feedback

**Comment by rtfeldman** [comment]
Thanks for talking it through! I really appreciate your patience. ♥️
