### ISSUE TITLE
Idea: Ability to isolate or skip a test

### ISSUE THREAD

**Issue by benansell** [elm-community/elm-test#44]
Often it is convenient to ether:
* ignore one or more tests
* only run a few tests

Currently if you can use a well placed and crafted Test.filter can be used to achieve both. However, this can be initially non-obvious to new users and tricky to quickly get right without always reverting to changing the test description. In addition, there is no indication in the output that some tests have been skipped - which can become an issue over time on larger projects without a method of reporting on the number of skipped tests.

I was wondering if there was a reason that the following syntax is not supported:

```elm
    describe "Troublesome feature"
        [ test "normal test" <|
            \() -> Expect.pass
        , ignore test "ignored because I always fail!" <|
            \() ->
                Expect.fail "Ignored test failure"
        ....
       ]
```

I think this would provide a quick convenient way for people to ignore tests, while providing a mechanism by which failures can be reported at the end of the test run:

```
Passed:  1
Failed:  0
Ignored: 1
``` 
CI builds can then be setup to monitor these output's / statistics over time.

Conversely it would also be nice to have the opposite with the same convenience, e.g. by adding "only" in front of a test / describe - that would then cause the test runner to just run tests / describes that have an only prefix, and show all the other tests as ignored in the output.

I have add a go at adding the ignore part to the code to see what the impact would be [here] (https://github.com/benansell/elm-test/tree/add-ignore) - note this currently does not work with fuzz tests.

What are peoples thoughts on this change to the API?

**Comment by mgold** [comment]
Coming from rspec, the word for "only" is "focus". There's also a way to mark tests as "pending", neither passed nor failed; "skip" is also a good choice.

As you've discovered, getting this to work with fuzz tests will require a bit of cleverness:
```elm
-- You can't implement 'skip' and have both of these compile:
skip unit "descr" <| \() -> testBody
skip fuzz int "descr" <| \i -> fuzzBody

-- But this should work
skip aTest = Internal.Skipped (Internal.getDescription aTest)
skip <| unit "descr" <| \() -> testBody
skip <| fuzz int "descr" <| \i -> fuzzBody
```

More philosophically, skipping and isolating tests makes for a more brittle test suite. It's too easy to commit a test suite with only one test actually running, or to leave dead code in a permanent skip state. elm-test aims to be performant so, until we get data to the contrary, I don't think we should worry about running only parts of a test suite. For the specific case of focusing on a particular test, the idea of a "guard mode" has been brought up. I much prefer storing this state in the runner rather than in the test suite code.

**Comment by benansell** [comment]
Thanks for the feedback.

As you point out there are many different words for the same same concept - I don't think it matters which ones are used provided they have clear meaning.

I agree that using <| would work, it's just that when using elm-format (I have it set to run on file save), the test code gets re-formatted when you add focus / skip - which is something I was trying to avoid as it can make it harder to pin down what actually changed.

On the philosophical side I agree with the ideal of never having an ignored test in code. However, sadly I have often been in the situation where a test needs to be disabled for a few weeks / months while an external issue is resolved. In which case I think the following would work well (even though it re-formats):

``` elm
skip "waiting for blah to be fixed"  <| unit "descr" <| ....
```

I also agree that an easy way to ignore tests can make the whole suite brittle through an accidental checkin and I have previously had to setup CI tasks to spot such issues. Interestingly Test.filter does this at the moment and it's effect is hidden in the output summary, making any CI checks for usage a little more tricky. 

Finally, I like the idea of moving focus into the runners as most of the reason for skipping / focusing on a test is during dev work - but I'm not sure about the ease of doing this in a runner without the tests being represented graphically (as a tree?) - do you know if any runners are working on this?

**Comment by mgold** [comment]
> the test code gets re-formatted when you add focus / skip

I think elm-format will allow `<|`s to pile up on one line.

> a test needs to be disabled for a few weeks / months while an external issue is resolved

Comment it out?

> Interestingly Test.filter does this at the moment and it's effect is hidden in the output summary

`Test.filter` is slightly less dangerous than this proposal since it's a little bit harder to add. I agree perhaps we should report the number of skipped tests-- but that might encourage people to use `Test.filter` more.

> do you know if any runners are working on this?

No.

There are several dozen features we hypothetically add, and we're looking to see which ones will help a real-world pain point and which ones just sound nice.

**Comment by zkessin** [comment]
I think it was QUnit that by default would run whatever test failed last time first when you ran it again. Might be a good feature, if you test suite takes more than a fraction of a second to run to run whatever test failed most recently first.

**Comment by mgold** [comment]
>  run whatever test failed last time first when you ran it again

rtfeldman/node-test-runner#51

**Comment by benansell** [comment]
@mgold feel free to close this issue.
