### ISSUE TITLE
Fuzz.filter

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#57]
@rtfeldman asked for `Fuzz.filter` to not be released in 2.1.0 because of concerns over the infinite looping behavior when all or nearly all values are filtered out. Adding it back involves reverting commits 6d08f19705bbc7468b25a7498125188345e8b0df and c0440ad04fd1c176b64e9439fddc53def12bf62b. Although I think the looping behavior is fine as long as it's well-documented, it's also one of the motivating cases for #56, invalid fuzzers.

Also, it wouldn't be hard to add `Fuzz.filterMap : (a -> Maybe b) -> Fuzzer a -> Fuzzer b`.

If anyone in the community would find these functions useful or has an opinion on the looping behavior, please comment and let us know!

**Comment by zkessin** [comment]
I would find it useful. 

In erlang https://github.com/triqng/triq we have two macros for this ?SUCHTHAT which will eliminate invalid cases, and fail if not enough valid cases are found, and ?SUCHTHATMAYBE which will start to feed invalid cases if it can't find valid ones.

I think having a filter of the form `filter : (a -> Bool) -> Fuzzer a -> Fuzzer a` makes a great deal of sense. ( or call it "suchthat")

**Comment by drathier** [comment]
It could have a maximum number of consecutive failed attempts, at which point it fails the test with an error like "couldn't find an acceptable input". 

It would make the probability of failing a fuzz test that has a small unhandled edge case (like checking that sha1(a) != sha1(b) when a != b) go way down for, say, 10 retries. 

Python Hypothesis has `assume` for this purpose. https://hypothesis.readthedocs.io/en/latest/details.html?highlight=assume#making-assumptions Haskell's Quickcheck also has this feature.

**Comment by rtfeldman** [comment]
For small unhandled edge cases, it seems better to just make them pass. ☺️

That slightly reduces the (arbitrarily chosen) number of useful tests that get run, which seems like a less serious drawback than potentially not terminating - or adding further complexity to avoid not terminating!

**Comment by drathier** [comment]
Sure, that's the pragmatic solution, but if I accidentally assume false, I would like the fuzzer to tell me :) There's an interesting difference between "all tests passed" and "nothing was actually tested". 

`assume x < 0 and y > 0` typo'd into `assume x < 0 and x > 0` could be interesting.

**Comment by mgold** [comment]
I've never seen `assume` before and it looks very useful. However, the implementation seems (I haven't actually looked) to rely heavily on exceptions, while fuzzers are built on the idea that they always return a value to test.

The only way out I can see is co-opting Debug.crash as an "exception" which the instrumenting code can catch. This seems incredibly hacky, will couple `elm-test` and the node runner, is likely not possible in the pure Elm html-runner, and likely falls under "further complexity to avoid not terminating" Richard mentioned above.

So, I don't see how that would be worth it.

**Comment by drathier** [comment]
@mgold you could just return a special Expect value using an if-statement or similar. `if a < 2 then Expect.anotherInput else *the actual test*`. No need for exceptions.

**Comment by mgold** [comment]
Moving this from the fuzzer level to the expectation level isn't a bad idea, but it would require changing some of the internal types.

First, a test is

```elm
type Test
    = Test (Random.Seed -> Int -> List Expectation)
```

It takes a random seed, the number of times to run the test (i.e 1 for unit tests and 100 by default for fuzz tests), and gives you back a list of expectations. There is no way to distinguish between fuzz tests and unit tests here; unit tests just ignore the initial seed. We get back the list of expectations, but not another random seed, though that could be changed.

And `Expectation` itself is defined as either a pass or a failure, though #85 wants to enrich the representation. It would be possible to add a `NeedsAnotherInput` tag, which would likely hold the function to run the test. Then we'd iterate over the list of expectations and rerun the test with a new seed.

Point being, I think this is *possible*, but difficult and not yet justified by use cases.

Given the way we map over fuzzers, it is not possible at all to do what python does when it tries to provide values that haven't been filtered, instead of just new values.

**Comment by mgold** [comment]
Here's a somewhat compelling use case from [Stackoverflow](http://stackoverflow.com/questions/41034482/assume-a-b-with-elm-fuzz-tests): given two inputs, make sure they are not equal.

Ideally this would be as simple as

```elm
fuzz int int "example" <| \a b ->
  if a == b then
    Expect.reroll
  else
    -- actual test
```

**Comment by rtfeldman** [comment]
Here is an API that seems like it would handle that use case, while being guaranteed to terminate:

```elm
conditional : Int -> (a -> Expectation) -> (a -> Bool) -> Fuzzer a -> Fuzzer a
conditional maxAttempts fallback predicate fuzzer =
```

In the StackOverflow example, you'd do this:

```elm
Fuzz.conditional
    1000 -- Try this up to 1000 times before giving up
    (\( first, second ) -> ( first, first % second )) -- fall back on derived value 
    (\( first, second ) -> first /= second ) -- keep generating until this is True or we run out of attempts
    (Fuzz.tuple Fuzz.int Fuzz.int) -- use this for each try
```

This is less easy to use because it demands that you describe what to do if things go poorly.

That seems like the best way to handle this. After all, this seems to be a rare use case, so it's not like people would need to define a ton of these. I like this better than making it easy to write flaky tests!

**Comment by drathier** [comment]
@mgold yes, I wrote that question. `Expect.reroll` seems like a good way to do it, but I get that it's bad to write flaky test cases, both in the infinite loop case and the "nothing got tested" case. The whole point of this feature is to reduce the probability of tests flaking out, possibly to 0. 

@rtfeldman Your `conditional` version is better after something is checked in in a large codebase, since those small probabilities add up. It's not always possible to derive a good input from a bad one, so we might end up with what is actually unit tests. Also, if it is possible to derive a good input from a bad one, why don't we do that for all bad inputs?

For both, I would still like to know if a test completely failed to generate a good input, and possibly if it had a really hard time doing so (maybe if >50% of generated values were rejected). When developing fuzz tests, it would be useful to get some feedback. 

We can't really have both, so do we prefer the case where no fuzz tests were run, because no valid input was found, or the infinite loop?

**Comment by rtfeldman** [comment]
> Also, if it is possible to derive a good input from a bad one, why don't we do that for all bad inputs?

Because [as you put it](http://stackoverflow.com/questions/41034482/assume-a-b-with-elm-fuzz-tests), "I do not want to make them not equal by deriving the second input from the first as this severely limits the search space."

This lets you have a much bigger search space, while falling back on an acceptable (but limited-search-space) default if the improbable happens.

## Opt-in flakiness

This would be a alternative to the above:

```elm
conditional : Int -> (a -> Result String a) -> (a -> Bool) -> Fuzzer a -> Fuzzer a
```

The difference is the `(a -> a)` fallback function becoming `(a -> Result String a)` - allowing you to return `Err "unable to generate a satisfactory Foo after 1000 attempts"` if you'd like the test to fail in the event that we run out of attempts.

However, I know from experience that flaky tests are one of the most frustrating plagues that can afflict a team. If this feature existed on our team, I'm pretty sure we'd immediately adopt a rule never to use it.

That suggests to me that it'd be better not to do it, and to instead stick with `a -> a` for the fallback.

**Comment by drathier** [comment]
@rtfeldman Ok, you've convinced me. By deriving a good case from a bad one, we know that the test runs at least once, which pretty much takes care of the case I was worried about. 

I vote for this:
```elm
conditional : Int -> (a -> a) -> (a -> Bool) -> Fuzzer a -> Fuzzer a
conditional maxAttempts fallback predicate fuzzer =
```

**Comment by rtfeldman** [comment]
@mgold thoughts on this? ☝️

**Comment by mgold** [comment]
☝️ Them's ma thoughts.
