### ISSUE TITLE
Fuzz.andThen generating an infinite sequence of shrunken values

### ISSUE THREAD

**Issue by zkessin** [elm-community/elm-test#62]
see the code in this Gist
https://gist.github.com/zkessin/1ad4a1a972dbd95be64a83a2a728a36e

when I try to run it I get 
```

Running 1 test. To reproduce these results, run: elm-test --seed 255629636

A: 96
State : (96,336)
A: 0
A: 48
A: 0
A: 24
A: 0
A: 12
A: 0
A: 6
A: 0
A: 3
````

Except that that sequence goes on forever (or at least until I kill it or get an out of memory error)

**Comment by robertjlooby** [comment]
My guess is it can't be shrunken because the second part of the tuple depends on the first

https://github.com/elm-community/elm-test/blob/d597f1c4e94e93f37211df4aaa866131bcdc58f0/src/Fuzz.elm#L451-L457

"A number `n` and another number `n <= n' <= n + 500`" seems to be the same type of "pathological predicate" described there.

**Comment by mgold** [comment]
Yeah, I'm going to say that's unsupported, partially because there's a lot of complicated code interacting here, and partially because there's an easy workaround. You've likely figured out that you can instead do

```elm
tuple (intRange -500, 500) (intRange 0 500) |> map (\(a, offset) -> (a, a + offset))
```

**Comment by zkessin** [comment]
Ok, I am going to close this

**Comment by mgold** [comment]
The example in the gist terminates now. You get a lot of shrinks, but I think that's okay for this contrived example.
