### ISSUE TITLE
Expectations for Maybe and Result

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#67]
Each of these are around 7 lines of code to implement:

``` elm
Expect.nothing : Maybe a -> Expectation
Expect.just : (a -> Expectation) -> Maybe a -> Expectation

Expect.ok : (b -> Expectation) -> Result a b -> Expectation
Expect.err : (a -> Expectation) -> Result a b -> Expectation
```

Are they worth adding?

**Comment by zkessin** [comment]
I would say so.

**Comment by rtfeldman** [comment]
I'd say by default let's not. Prefer to keep the API surface area small unless there's a really compelling reason it needs to be expanded.

**Comment by rtfeldman** [comment]
Use case in the wild: I ended up using something like `Expect.err` in [`rtfeldman/hex`](https://github.com/rtfeldman/hex/blob/master/tests/Tests.elm#L229).

Interestingly, this implementation of `Expect.err` wouldn't have saved me much code, since I didn't care what the message was - I just cared that it was an `Err` of some sort. (I usually try to avoid situations where will tests break if I decide to rephrase an error message.)

`Expect.ok` would have been slightly more concise than `Expect.equal (Ok ...`](https://github.com/rtfeldman/hex/blob/master/tests/Tests.elm#L189) - but I'm honestly not sure if I would have bothered. I like using `Expect.equal` wherever possible, and I'm skeptical that `.nothing`, `.just`, and `.ok` are worth expanding the API just to save a few characters.

Having said that, a `.err` function that conveys "I want an `Err` of some sort, but I don't care what's inside" seems pretty useful! That's something you can't easily get using `Expect.equal`.

Based on this, I'm inclined to say we should merge [this implementation](https://github.com/rtfeldman/hex/blob/master/tests/Tests.elm#L229) as `Expect.err` and leave the others out for now.

Thoughts?

**Comment by zkessin** [comment]
I would rather have the full set myself

**Comment by rtfeldman** [comment]
@zkessin My general design philosophy is to prioritize avoiding API bloat. This means I view every new addition as a mistake until proven otherwise.

I [made a case](https://github.com/elm-community/elm-test/issues/67#issuecomment-264788218) for why I think `Expect.err` makes sense but `Expect.ok`, `Expect.just`, and `Expect.nothing` are not worth expanding the API.

If you feel differently, please come at this from the perspective of the value these functions would provide over the status quo where they don't exist.

If all they save is a few letters, e.g. `Expect.equal (Ok foo))` versus `Expect.ok foo`, that does not seem like a compelling enough reason to expand the API to me—especially when people will still need to use `Expect.equal (MyUnionType foo)` for everything other than `Result` and `Maybe` anyway.

**Comment by zkessin** [comment]
makes sense, if all else fails there are a few extra packages that can be used, I saw a function somewhere that did Result -> Bool so that should solve the problem

**Comment by mgold** [comment]
Yes, I think it's far more common to say "I expect a failure of some kind but don't care what it is" than to do the same for the success case. It's slightly obscured by the fact that `Expect.nothing` isn't needed, because we have `Expect.equal Nothing`.

**Comment by mgold** [comment]
Marking as help wanted to indicate there is a clear code contribution we're ready to accept.

**Comment by mgold** [comment]
I went ahead and implemented this based off the branch for #85, so it's ready once that's merged.

**Comment by rtfeldman** [comment]
@mgold `err` or all four of them? (I think we only want `err`.)

**Comment by mgold** [comment]
Just `err`!

**Comment by alvivi** [comment]
I have a full test suite that requires expectations for `Maybe` and `Result`. I don't care about the value inside these functors, so using the same reasoning that @rtfeldman, an `ok` and a `just` expectations that don't inspect the contained value seems valuable. Indeed, having an `err` and not an `ok` feels kind of weird for a bifunctor type. If API bloat is a problem, then maybe adding a `not : Expectation -> Expectation` could be a solution because:

```
just = (Expect.equal Nothing) >> Expect.not
ok = Expect.err >> Expect.not
```

**Comment by mgold** [comment]
The problem with `not` is that we require the reason why a test failed, but not why it passed. So inverting that and we have no reason why a not-test failed, other than the fact that it was a not-test. We have something similar to this in the tests for elm-test itself (implemented using not-exposed packages), so I can say from experience that this kind of error is not fun to work with.

Can you say more about your use case? We want to add functions that are useful in practice, not because their absence "feels kind of weird".

**Comment by alvivi** [comment]
@mgold you are right. Playing with `not` message will be tricky. 

My test cases are about values that should not suppose an error or a particular case for a function. For example, If I have some kind `hash : String -> Maybe Int` and I want to require that the empty string must have a valid value, I should be able to say that `Expect.just (hash "")`, without worrying about the value. The same applies to `Result`.

Maybe another solution will be creating another package, `elm-test-expect-extra` or something similar wich adds all kind of expectations for core types. Including the `err` expectation.

**Comment by mgold** [comment]
> If I have some kind `hash : String -> Maybe Int` and I want to require that the empty string must have a valid value

Try `hash "" |> Expect.notEqual Nothing`. This doesn't work if you have a Result and expect some kind of okay value, though.

> Including the `err` expectation.

The `err` expectation has been merged, and adding it to a third-party lib would just confuse things.

If you feel the need, you can always define your own little helper using a `case` expression, `Expect.pass`, and `Expect.fail`. That's why they're exposed.

**Comment by alvivi** [comment]
@mgold Thanks for the hint! I will do that.
