### ISSUE TITLE
Skip/Only flags for Tests

### ISSUE THREAD

**Issue by baldore** [elm-community/elm-test#88]
It should be great to have a different function that is very similar, but that allows to disable or run only specific tests. For example, in Mocha you can use **describe.only** to run that suite of tests, or **describe.skip** to skip it. Let me know what do you think about it. 

I could be interested in make a pull request for this.

**Comment by mgold** [comment]
Seems reasonable. I think a reasonable syntax would be -- and I *think* this is possible in terms of types --
```elm
test "example" <| \() -> Expect.pass
-- becomes
skip <| test "example" <| \() -> Expect.pass
-- or
only <| test "example" <| \() -> Expect.pass
```
Rspec using "broken" and "focus" for this purpose but I like your words better.

Another possibility, supported by both rspec and jasmine, is prepending a letter to the name: `it` becomes `fit` to focus and `xit` to exclude. But I like using functions because they're reusable across unit, fuzz, fuzzN, and suites.

**Comment by benansell** [comment]
See #44 for a previous discussion on this topic.

@baldore - if this is something you need it is supported in [lobo-elm-test-extra](http://package.elm-lang.org/packages/benansell/lobo-elm-test-extra/latest)

**Comment by mgold** [comment]
Perfect! (We have an -extra library? Aren't we fancy...)

**Comment by baldore** [comment]
So nice!!! I'm gonna take a look at it. Thanks a lot!

**Comment by mgold** [comment]
Of course, if we supported them directly we could give better output on skipped or isolated tests.

**Comment by rtfeldman** [comment]
I'd rather not add these.

In my experience, these end up being a way to comment out tests without the dirty feeling that comes with commenting things out. I think that's a bug, not a feature.

Whenever I've worked on a large code base in a testing environment that supported this, we ended up with `xit` and `xdescribe` tests hanging around for months or longer. I've never seen "X tests pending" be a serious deterrent. A cursory glance of our repo at work right now reveals that we still have several of these from our legacy JS tests, including one that's stuck around since 2013.

Sure, commented-out things get left hanging around too, but commented-out code has the feature of being visually repellant. If someone comes along a big block of commented-out tests later, they will likely have a visceral reaction that makes them want to either fix the tests or delete them. That's a good reaction to have for technical debt.

In contrast, nothing looks broken about `xit`. It's technical debt that's easy to ignore. I don't think that's a feature; I think that's a bug.

So I don't think we should add it. 🙂
